name: TestVersion

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
   build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        smalltalk: 
          - Pharo64-8.0
          - Pharo64-7.0
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
